spring:
  application:
    name: Procedure Manager API

info:
  app:
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    name: '@project.name@'
    version: '@project.version@'
    java:
      version: '@java.version@'